name: Crypto Predictions

on:
  # push:
  #   branches:
  #     - "**" # alle Branches (inkl. Feature-Branches)

  # Optional: nur laufen, wenn relevante Files geändert wurden
  # paths:
  #   - "moonshot_scan.py"
  #   - "requirements.txt"
  #   - ".github/workflows/moonshot-scan.yml"

  # pull_request:
  #   branches:
  #     - "**"

  workflow_dispatch: {} # manueller Start (branchauswahl im UI)

  schedule:
    - cron: "55 5 * * *" # 07:40 Uhr CEST (Sommerzeit), entspricht 05:40 UTC
    # - cron: "*/5 * * * *" # alle 5 Minuten (Testzwecke, entfernen für produktiven Einsatz)

permissions:
  contents: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Prediction
        run: python crypto_analysis.py

      - name: Commit report if changed
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add crypto_analysis_report.md || true
          git add crypto_predictions.json || true

          if ! git diff --cached --quiet; then
            git commit -m "chore: update crypto analysis report [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
